baseURL = "https://revolution1000.github.io/"
languageCode = "en-us"
title = "My Site"
theme = "ananke"

[params]
author = "Christopher"
description = "My personal website"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3