baseURL = "https://revolution1000.github.io/myblog/"
languageCode = "en-us"
title = "歌未竟"
theme = "ananke"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
  name = "Mathematics"
  url = "/categories/mathematics/"
  weight = 1

  [[menu.main]]
  name = "Physics"
  url = "/categories/physics/"
  weight = 2

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

[params]
  author = "Your Name"
  description = "Notes on Mathematics and Physics"
  show_reading_time = true
  show_post_nav_links = true
  background_color_class = "bg-black"